"""PDF evidence report generation with per-module findings."""
import json
import logging
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.pdfgen import canvas

from ..core.config import settings

logger = logging.getLogger(__name__)

RIGHT, TOP_MARGIN = A4[0] - 2 * cm, A4[1] - 2 * cm


def _wrap(text: str, max_width, font, fontsize, canvas_obj):
    """Wrap text into lines that fit max_width, return list of lines."""
    canvas_obj.setFont(font, fontsize)
    words = text.split()
    lines, cur = [], ""
    for word in words:
        trial = (cur + " " + word).strip()
        if canvas_obj.stringWidth(trial, font, fontsize) <= max_width:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    return lines


def write_pdf_report(doc, record, breakdown, citation_result, statistics_result, writing_result, report_name):
    """Write a detailed evidence PDF for the analysis record."""
    output_path = settings.REPORTS_DIR / report_name
    settings.REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    c = canvas.Canvas(str(output_path), pagesize=A4)
    width = A4[0]
    y = TOP_MARGIN

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2 * cm, y, "VeriPaper — Research Verification Report")
    y -= 10
    c.setFont("Helvetica", 9)
    c.drawString(2 * cm, y, f"File: {record.filename}  |  {record.word_count} words  |  Analyzed {record.analyzed_at:%Y-%m-%d %H:%M UTC}")
    y -= 18

    # Verdict box
    verdict_colors = {"Credible": colors.green, "Needs review": colors.orange, "High risk": colors.red}
    color = verdict_colors.get(record.verdict, colors.grey)
    c.setFillColor(color)
    c.roundRect(2 * cm, y - 30, width - 4 * cm, 36, 6, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(2 * cm + 12, y - 22, f"{record.verdict} — overall credibility {record.overall_research_credibility}/100")
    c.setFont("Helvetica", 9)
    c.drawCentredString(width / 2, y - 14, "Scores are assistive likelihood signals, not conclusive proof of misconduct.")
    y -= 52
    c.setFillColor(colors.black)

    sections = [
        ("AI Generation Detection", [
            f"AI-likelihood score: {record.ai_probability}% (confidence: {record.ai_confidence})",
            f"Engine: {record.ai_engine}",
        ]),
        ("Similarity (Plagiarism) Check", [
            f"Similarity score: {record.plagiarism_score}/100",
        ] + ([f"Match: {m['title']} ({m['similarity']}%)" for m in
              (json.loads(record.plagiarism_matches) if record.plagiarism_matches else [])][:5])),
        ("Citation Validation", [
            f"Validity score: {record.citation_validity_score}/100",
            f"DOIs checked: {json.loads(record.citation_details).get('total_dois', 0) if record.citation_details else 0} "
            f"(valid: {json.loads(record.citation_details).get('valid_dois', 0) if record.citation_details else 0})",
        ]),
        ("Statistical Integrity", [
            f"Risk score: {record.statistical_risk_score}/100 — {statistics_result.summary}",
        ] + [f"• {f.category}: {f.detail}" for f in statistics_result.findings][:4]),
        ("Academic Writing Standards", [
            f"Writing quality: {record.writing_quality_score}/100 ({writing_result.grade})",
        ] + [f"• {'PASS' if ck['passed'] else 'FAIL'} {ck['name']}: {ck['detail']}" for ck in
             (json.loads(record.writing_checks) if record.writing_checks else [])]),
    ]

    for title, lines in sections:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(2 * cm, y, title)
        y -= 13
        c.setFont("Helvetica", 9)
        for line in lines:
            wrapped = _wrap(line, width - 4 * cm, "Helvetica", 9, c)
            for wline in wrapped:
                if y < 3 * cm:
                    c.showPage()
                    y = TOP_MARGIN
                    c.setFont("Helvetica", 9)
                c.drawString(2 * cm + 6, y, wline)
                y -= 12
        y -= 8

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(2 * cm, 1.4 * cm, "Generated by VeriPaper. This report is assistive evidence only.")
    c.showPage()
    c.save()
    logger.info("Report written: %s", output_path)
