import { Component, useEffect, useMemo, useState } from "react";
import { analyzePaper, analyzePaperAsync, pollUntilDone, fetchHistory, fetchHistoryItem, fetchConfig } from "./api";
import { downloadPDF, downloadCSV, downloadJSON, saveToHistory, getHistory, clearHistory } from "./utils";

/* ------------------------------------------------------------------ */
/* Error boundary — a panel crash shows a friendly message, never a   */
/* blank screen.                                                       */
/* ------------------------------------------------------------------ */

class ErrorBoundary extends Component {
  constructor(props) {
    super(props);
    this.state = { err: null };
  }
  static getDerivedStateFromError(err) {
    return { err };
  }
  render() {
    if (this.state.err) {
      return (this.props.fallback || (() => null))(this.state.err);
    }
    return this.props.children;
  }
}

const VERDICT_META = {
  "Credible": { badge: "bg-emerald-100 text-emerald-800 border-emerald-200", title: "Looks Credible", desc: "This paper passes the checks well. It can move forward in review, keeping in mind these are likelihood signals, not proof." },
  "Needs review": { badge: "bg-amber-100 text-amber-800 border-amber-200", title: "Needs Review", desc: "Some checks raised mild concerns. A human reviewer should look at the flagged sections before accepting." },
  "High risk": { badge: "bg-red-100 text-red-800 border-red-200", title: "High Risk Signals", desc: "Strong integrity concerns were detected. Prioritize manual investigation of the flagged issues." },
};

function verdictMeta(verdict) {
  return VERDICT_META[verdict] || { badge: "bg-slate-100 text-slate-700 border-slate-200", title: verdict || "Pending", desc: "Analysis complete." };
}

function riskLabel(score, invert = false) {
  const v = invert ? 100 - score : score;
  if (v < 30) return { text: "Low concern", cls: "text-emerald-700", bar: "bg-emerald-500" };
  if (v < 60) return { text: "Moderate", cls: "text-amber-700", bar: "bg-amber-500" };
  return { text: "High concern", cls: "text-red-700", bar: "bg-red-500" };
}

const MODULE_TITLES = {
  plagiarism: "Similarity & Plagiarism",
  ai_detection: "AI-Written Content",
  citation: "Citation Authenticity",
  statistics: "Statistical Integrity",
  writing: "Writing & Standards",
  provenance: "Provenance Chain Verification",
};

const MODULE_EXPLAIN = {
  plagiarism: "Compares your paper against an indexed corpus of 2,500+ open-access abstracts (semantic similarity) and scans for duplicated text between the paper's own sections. Higher score = more overlap found.",
  ai_detection: "A fine-tuned DistilBERT model, trained on 3,600 real arXiv abstracts versus controlled AI rewrites, estimates the probability that the text was generated by an AI. Higher = more AI-like.",
  citation: "Every DOI is checked live against the CrossRef registry. Missing or invalid DOIs reduce the score, because fabricated references are a common integrity red flag.",
  statistics: "Looks for unrealistic numeric patterns — suspiciously clean p-values, round percentages, and implausible results — that often appear in manipulated reporting.",
  writing: "Checks the paper against academic conventions: required sections, formal tone, consistent citation style, citation-text linkage, figure/table references, and heading hierarchy.",
  provenance: "VeriPaper's flagship check: traces every claim to its cited origin and stress-tests the evidence base. It blends retraction-contamination tracing (live against Retraction Watch via CrossRef), citation-graph coherence, claim-to-citation alignment, and statistical forensics (Benford's law, p-curve, impossible-precision detection). Optional web-source attribution needs a BRAVE_API_KEY on the server.",
};

function GradeGauge({ score, size = 96 }) {
  const r = (size - 12) / 2;
  const c = 2 * Math.PI * r;
  const offset = c * (1 - Math.min(100, Math.max(0, score)) / 100);
  return (
    <div className="relative inline-flex items-center justify-center" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-90">
        <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="#e2e8f0" strokeWidth={8} />
        <circle
          cx={size / 2} cy={size / 2} r={r} fill="none"
          stroke={score >= 70 ? "#10b981" : score >= 45 ? "#f59e0b" : "#ef4444"}
          strokeWidth={8} strokeLinecap="round"
          strokeDasharray={c} strokeDashoffset={offset}
          style={{ transition: "stroke-dashoffset 0.8s ease" }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-xl font-bold text-slate-900">{Math.round(score)}</span>
        <span className="text-[10px] uppercase tracking-wide text-slate-500">/ 100</span>
      </div>
    </div>
  );
}

function ProgressBar({ value, color = "bg-blue-500" }) {
  return (
    <div className="w-full h-1.5 bg-slate-200 rounded-full overflow-hidden">
      <div className={`h-full rounded-full ${color}`} style={{ width: `${Math.min(100, Math.max(0, value))}%` }} />
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Module detail panels                                                */
/* ------------------------------------------------------------------ */

function PlagiarismPanel({ data }) {
  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-600">{data.summary}</p>
      <div className="grid grid-cols-2 gap-3">
        <div className="card bg-slate-50 border-slate-200">
          <p className="text-xs uppercase tracking-wide text-slate-500">Corpus matches</p>
          <p className="text-2xl font-bold text-slate-900">{data.matches.length}</p>
        </div>
        <div className="card bg-slate-50 border-slate-200">
          <p className="text-xs uppercase tracking-wide text-slate-500">Repeated paragraphs</p>
          <p className="text-2xl font-bold text-slate-900">{data.duplicate_paragraphs}</p>
        </div>
      </div>
      {data.matches.length > 0 && (
        <div>
          <p className="text-xs font-semibold text-slate-500 mb-2 uppercase tracking-wide">Matched sources</p>
          <div className="space-y-2">
            {data.matches.map((m, i) => (
              <div key={i} className="p-3 bg-slate-50 rounded-lg border border-slate-200">
                <p className="font-medium text-slate-900 text-sm">{m.title}</p>
                <p className="text-xs text-slate-500 mt-1">{Math.round(m.similarity)}% similar · {m.source}</p>
                <p className="text-xs text-slate-600 mt-2 italic">"{m.matched_text}"</p>
              </div>
            ))}
          </div>
        </div>
      )}
      {data.matches.length === 0 && (
        <p className="text-xs text-slate-500 bg-emerald-50 border border-emerald-200 rounded-lg p-3">
          No significant similarity to the indexed open corpus. Note: free-tier analysis checks a representative corpus of open-access literature, not the whole internet.
        </p>
      )}
    </div>
  );
}

function AIPanel({ data }) {
  const low = data.ai_probability < 38;
  const high = data.ai_probability > 62;
  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-600">
        {low
          ? "The text shows natural human writing patterns — varied sentence structure and organic rhythm that AI generators rarely reproduce."
          : high
            ? "The text shows strong AI-like regularity: unusually uniform sentence lengths, dense hedging phrases, and templated argument flow."
            : "Signals are mixed. The model cannot decide confidently — common for well-edited human text or lightly AI-assisted drafts."}
      </p>
      <div className="text-xs text-slate-500 space-y-1">
        <p><span className="font-semibold">Engine:</span> {data.engine === "transformer_finetuned" ? "Fine-tuned transformer (DistilBERT)" : data.engine}</p>
        <p><span className="font-semibold">Trained on:</span> 3,600 real arXiv abstracts vs. controlled AI rewrites</p>
        <p><span className="font-semibold">What it means:</span> this is a probability, not proof. Always treat as one signal among many.</p>
      </div>
    </div>
  );
}

function CitationPanel({ data }) {
  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-600">{data.summary}</p>
      <div className="grid grid-cols-3 gap-3">
        <div className="card bg-slate-50 border-slate-200">
          <p className="text-xs uppercase tracking-wide text-slate-500">Total DOIs</p>
          <p className="text-2xl font-bold text-slate-900">{data.total_dois}</p>
        </div>
        <div className="card bg-emerald-50 border-emerald-200">
          <p className="text-xs uppercase tracking-wide text-emerald-700">Verified</p>
          <p className="text-2xl font-bold text-emerald-800">{data.valid_dois}</p>
        </div>
        <div className="card bg-red-50 border-red-200">
          <p className="text-xs uppercase tracking-wide text-red-700">Invalid / missing</p>
          <p className="text-2xl font-bold text-red-800">{(data.invalid_dois?.length || 0) + data.references_without_doi}</p>
        </div>
      </div>
      {data.verified_dois?.length > 0 && (
        <div>
          <p className="text-xs font-semibold text-slate-500 mb-2 uppercase tracking-wide">Reference-by-reference</p>
          <div className="space-y-2">
            {data.verified_dois.map((d, i) => (
              <div key={i} className={`p-3 rounded-lg border text-xs ${d.valid ? "bg-emerald-50 border-emerald-200" : "bg-red-50 border-red-200"}`}>
                <p className="font-medium text-slate-900">{d.doi}</p>
                {d.title && <p className="text-slate-600 mt-1">{d.title}{d.year ? ` (${d.year})` : ""}</p>}
                <p className={d.valid ? "text-emerald-700" : "text-red-700"}>{d.valid ? "✓ Exists in CrossRef" : "✗ Not found in CrossRef — verify the source"}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function StatisticsPanel({ data }) {
  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-600">{data.summary}</p>
      {data.findings?.length > 0 ? (
        <div className="space-y-2">
          {data.findings.map((f, i) => (
            <div key={i} className={`p-3 rounded-lg border text-xs ${f.severity === "high" ? "bg-red-50 border-red-200" : f.severity === "medium" ? "bg-amber-50 border-amber-200" : "bg-slate-50 border-slate-200"}`}>
              <p className="font-semibold text-slate-900">{f.category} <span className="font-normal text-slate-500">· {f.severity}</span></p>
              <p className="text-slate-600 mt-1">{f.detail}</p>
            </div>
          ))}
        </div>
      ) : (
        <p className="text-xs text-slate-500 bg-emerald-50 border border-emerald-200 rounded-lg p-3">No suspicious numeric patterns detected in the reported results.</p>
      )}
    </div>
  );
}

/* Provenance Chain Verification panel — the flagship evidence-tracing check.
   Note: for the first four layers a HIGHER sub-score is worse (contamination,
   graph anomaly) while alignment and fingerprint use 100 = best. */
function ProvenancePanel({ data }) {
  if (!data) return <p className="text-sm text-slate-500">Provenance data is not available for this analysis.</p>;
  const sub = (
    { label, value, goodHigh, noteKey } = {}
  ) => {
    const v = typeof value === "number" ? value : 0;
    const bad = goodHigh ? 100 - v : v;
    const { text, cls, bar } = riskLabel(bad);
    return (
      <div className="card bg-slate-50 border-slate-200">
        <p className="text-[11px] uppercase tracking-wide text-slate-500">{label}</p>
        <p className="text-xl font-bold mt-1">{Math.round(v)}</p>
        <div className="h-1.5 w-full bg-slate-200 rounded-full mt-1.5 overflow-hidden">
          <div className={`h-full rounded-full ${bar}`} style={{ width: `${Math.min(100, Math.max(0, v))}%` }} />
        </div>
        <p className={`text-[11px] mt-1.5 ${cls}`}>{text}</p>
        {noteKey && <p className="text-[10px] text-slate-400 mt-1">{noteKey}</p>}
      </div>
    );
  };
  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-600">{data.summary}</p>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        {sub({ label: "Retraction contamination", value: data.contamination_score, goodHigh: false })}
        {sub({ label: "Citation-graph coherence", value: data.graph_anomaly_score, goodHigh: false })}
        {sub({ label: "Claim–citation alignment", value: data.alignment_score, goodHigh: true })}
        {sub({ label: "Statistical forensics", value: data.fingerprint_score, goodHigh: true })}
      </div>
      {(data.retracted_dois?.length || 0) > 0 && (
        <div className="space-y-2">
          <p className="text-xs font-semibold text-red-700 uppercase tracking-wide">⚠ Cited retracted research</p>
          {data.retracted_dois.map((d, i) => (
            <div key={i} className="p-3 bg-red-50 border border-red-200 rounded-lg text-xs">
              <p className="font-medium text-slate-900">{d.doi || "Unknown DOI"}</p>
              {d.retraction_date && <p className="text-slate-600 mt-0.5">Retracted {d.retraction_date}</p>}
              {d.notice_type && <p className="text-slate-500 mt-0.5">Notice: {d.notice_type}</p>}
              {d.reason && <p className="text-red-700 mt-0.5">{d.reason}</p>}
            </div>
          ))}
        </div>
      )}
      {(data.alignment_verdicts?.length || 0) > 0 && (
        <div className="space-y-2">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">Claim-by-claim alignment</p>
          {data.alignment_verdicts.map((v, i) => {
            const isAligned = v.alignment === "aligned";
            const isWeak = v.alignment === "weak";
            return (
              <div key={i} className={`p-3 rounded-lg border text-xs ${isAligned ? "bg-emerald-50 border-emerald-200" : isWeak ? "bg-amber-50 border-amber-200" : "bg-red-50 border-red-200"}`}>
                <p className="font-medium text-slate-900 break-all">{v.doi || "Referenced claim"} <span className={`ml-2 font-semibold ${isAligned ? "text-emerald-700" : "text-amber-700"}`}>{isAligned ? "✓ Aligned" : isWeak ? "⚠ Weak" : "✗ Unsupported"}</span></p>
                {v.reason && <p className="text-slate-600 mt-1">{v.reason}</p>}
                {typeof v.overlap === "number" && <p className="text-slate-500 mt-1">Lexical overlap with cited abstract: {Math.round(v.overlap * 100)}%</p>}
              </div>
            );
          })}
        </div>
      )}
      {data.web_summary && (
        <div className="space-y-2">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">Web source attribution {data.web_available ? "" : "(not configured)"}</p>
          {data.web_available ? (
            (data.web_matches?.length || 0) > 0 ? (
              <div className="space-y-2">
                {data.web_matches.map((m, i) => (
                  <div key={i} className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs">
                    <p className="font-semibold text-slate-900 truncate">
                      {m.title ? <a href={m.url} target="_blank" rel="noopener noreferrer" className="underline">{m.title}</a> : m.url}
                    </p>
                    {m.snippet && <p className="text-slate-600 mt-1 line-clamp-2">{m.snippet}</p>}
                    <div className="flex items-center gap-2 mt-1.5">
                      <div className="h-1.5 flex-1 bg-slate-200 rounded-full overflow-hidden">
                        <div className="h-full bg-indigo-500 rounded-full" style={{ width: `${Math.min(100, Math.max(0, m.similarity || 0))}%` }} />
                      </div>
                      <span className="text-slate-500">{Math.round(m.similarity || 0)}%</span>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-xs text-emerald-700 bg-emerald-50 border border-emerald-200 rounded-lg p-3">✓ No matching sources found on the open web.</p>
            )
          ) : (
            <p className="text-xs text-slate-500 bg-slate-50 border border-slate-200 rounded-lg p-3">{data.web_summary}</p>
          )}
        </div>
      )}
    </div>
  );
}

function WritingPanel({ data }) {
  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-2">
        {(data.checks || []).map((c, i) => (
          <span key={i} className={`text-xs px-2.5 py-1 rounded-full border ${c.passed ? "bg-emerald-50 text-emerald-700 border-emerald-200" : "bg-amber-50 text-amber-700 border-amber-200"}`}>
            {c.passed ? "✓" : "⚠"} {c.name}
          </span>
        ))}
      </div>
      <div className="space-y-3">
        {(data.checks || [])
          .filter((c) => !c.passed)
          .map((c, i) => (
            <div key={i} className="p-3 bg-amber-50 border border-amber-200 rounded-lg">
              <p className="text-sm font-semibold text-amber-900">{c.name}</p>
              <p className="text-xs text-amber-800 mt-1">{c.detail}</p>
              {c.suggestions?.length > 0 && (
                <p className="text-xs text-amber-700 mt-1"><span className="font-semibold">Fix:</span> {c.suggestions[0]}</p>
              )}
            </div>
          ))}
        {(data.checks || []).filter((c) => !c.passed).length === 0 && (
          <p className="text-xs text-slate-500 bg-emerald-50 border border-emerald-200 rounded-lg p-3">All writing-standards checks passed.</p>
        )}
      </div>
      {Object.keys(data.section_map || {}).length > 0 && (
        <div>
          <p className="text-xs font-semibold text-slate-500 mb-2 uppercase tracking-wide">Detected structure</p>
          <div className="flex flex-wrap gap-1.5">
            {Object.values(data.section_map).map((h, i) => (
              <span key={i} className="text-[11px] px-2 py-0.5 bg-slate-100 text-slate-600 rounded">{h}</span>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Main App                                                            */
/* ------------------------------------------------------------------ */

/* Rebuild the nested result shape from a flat history record so the
   module panels can render a replay without crashing on undefined data. */

function flatRecordToResult(record) {
  const score = (v, fallback = 0) => (typeof v === "number" && Number.isFinite(v) ? v : fallback);
  return {
    id: record.id,
    filename: record.filename,
    word_count: record.word_count,
    section_count: 0,
    sections: [],
    overall_research_credibility: score(record.overall_research_credibility),
    verdict: record.verdict,
    report_path: record.report_path,
    analyzed_at: record.analyzed_at,
    action_items: [],
    risk_triggers: [],
    plagiarism: {
      score: score(record.plagiarism_score),
      summary: "Replay of a stored analysis — detailed source matches are not kept after the original scan completes (papers are never permanently stored).",
      matches: [],
      duplicate_paragraphs: 0,
    },
    ai_detection: {
      ai_probability: score(record.ai_probability),
      confidence: record.ai_confidence,
      engine: record.ai_engine,
    },
    citation: {
      validity_score: score(record.citation_validity_score),
      summary: "Replay of a stored analysis — per-reference details are not kept after the original scan completes.",
      total_dois: 0,
      valid_dois: 0,
      invalid_dois: [],
      references_without_doi: 0,
      verified_dois: [],
    },
    statistics: {
      risk_score: 100 - score(record.statistical_risk_score),
      summary: "Replay of a stored analysis — numeric findings are not kept after the original scan completes.",
      findings: [],
    },
    writing: {
      score: score(record.writing_quality_score),
      checks: [],
    },
    provenance: buildReplayProvenance(record),
  };
}

function buildReplayProvenance(record) {
  const score = (v, fallback) => (typeof v === "number" && Number.isFinite(v) ? v : fallback);
  const details = record.provenance_details || {};
  if (record.provenance_score == null && !details) return null;
  return {
    score: score(record.provenance_score, 50),
    summary:
      details.summary ||
      "Replay of a stored analysis — detailed provenance evidence is not kept after the original scan completes.",
    contamination_score: details.contamination_score ?? 50,
    graph_anomaly_score: details.graph_anomaly_score ?? 50,
    alignment_score: details.alignment_score ?? 50,
    fingerprint_score: details.fingerprint_score ?? 50,
    contamination_summary: details.contamination_summary || "",
    retracted_dois: details.retracted_dois || [],
    alignment_verdicts: details.alignment_verdicts || [],
    fingerprint_notes: details.fingerprint_notes || {},
    graph_density: details.graph_density || 0,
    isolated_references: details.isolated_references || 0,
    web_matches: details.web_matches || [],
    web_summary: details.web_summary || "",
    web_available: details.web_available === true,
  };
}

export default function App() {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [openModule, setOpenModule] = useState("ai_detection");
  const [config, setConfig] = useState(null);
  const [serverHistory, setServerHistory] = useState([]);
  const [localHistory] = useState(getHistory());
  const [showOnboard, setShowOnboard] = useState(false);
  const [replayError, setReplayError] = useState("");
  const [replayLoading, setReplayLoading] = useState(false);

  const modulePanelFallback = () => (
    <div className="p-6 text-center">
      <p className="text-sm font-medium text-slate-900">This detail could not be shown</p>
      <p className="text-xs text-slate-500 mt-2 max-w-md mx-auto">
        The detailed data for this older analysis is not kept on the server (papers are never stored). The overview scores above are still accurate — for a full replay, re-upload the paper.
      </p>
    </div>
  );

  useEffect(() => {
    fetchConfig().then(setConfig).catch(() => {});
    fetchHistory()
      .then((data) => setServerHistory(Array.isArray(data) ? data : data?.results ?? []))
      .catch(() => {});
    if (!localStorage.getItem("veripaper_onboarded")) {
      setShowOnboard(true);
    }
  }, []);

  const modules = useMemo(() => {
    if (!result) return [];
    return [
      { key: "plagiarism", score: result.plagiarism?.score ?? 0, invert: true },
      { key: "ai_detection", score: result.ai_detection?.ai_probability ?? 0 },
      { key: "citation", score: result.citation?.validity_score ?? 0 },
      { key: "statistics", score: 100 - (result.statistics?.risk_score ?? 0), invert: true },
      { key: "writing", score: result.writing?.score ?? 0 },
      { key: "provenance", score: result.provenance?.score ?? 0 },
    ];
  }, [result]);

  const vMeta = useMemo(() => (result ? verdictMeta(result.verdict) : null), [result]);

  const runAnalysis = async (e) => {
    e.preventDefault();
    if (!file) { setError("Please select a paper first (PDF, DOCX or TXT)."); return; }
    if (file.size > 15 * 1024 * 1024) { setError("File is larger than 15 MB."); return; }
    setError("");
    setLoading(true);
    setResult(null);
    setProgress(8);

    const timers = [];
    try {
      // Start async analysis
      setProgress(10);
      const { task_id } = await analyzePaperAsync(file);

      // Poll for completion with progress feedback
      const resultData = await pollUntilDone(
        task_id,
        (status) => {
          if (status.status === "queued") setProgress(15);
          else if (status.status === "processing") setProgress(50);
        },
        800,
        120000
      );

      const data = resultData.result;
      setProgress(100);
      setResult(data);
      saveToHistory(data);
      setServerHistory((prev) => [
        { id: `analysis_${Date.now()}`, filename: data.filename, analyzed_at: new Date().toISOString(), overall_research_credibility: data.overall_research_credibility, verdict: data.verdict },
        ...prev,
      ].slice(0, 15));
      setOpenModule("ai_detection");
    } catch (err) {
      setError(friendlyError(err, "Analysis failed. Please try again."));
    } finally {
      timers.forEach(clearTimeout);
      setLoading(false);
    }
  };

  /* Convert any API error payload into a human-readable string, so the
     UI never shows a raw "[object Object]" from FastAPI validation lists. */
  const friendlyError = (err, fallback) => {
    const raw = err?.response?.data?.detail ?? err?.message ?? fallback;
    if (typeof raw === "string") return raw;
    if (Array.isArray(raw)) {
      // FastAPI validation errors: [{loc, msg, type}, ...]
      const first = raw[0];
      if (first && typeof first.msg === "string") return first.msg;
      return String(raw[0] ?? fallback);
    }
    if (raw && typeof raw.msg === "string") return raw.msg;
    if (raw && typeof raw.detail === "string") return raw.detail;
    return fallback;
  };

  const openOld = async (entry) => {
    setError("");
    setReplayError("");
    // Only server-side rows have numeric ids; local/browser copies and the
    // ephemeral preview rows use string ids that the API cannot resolve.
    const recordId = Number(entry.id);
    if (!Number.isFinite(recordId)) {
      setReplayError("This entry was saved in your browser only — re-upload the paper for a fresh verification.");
      return;
    }
    setReplayLoading(true);
    try {
      const record = await fetchHistoryItem(recordId);
      setResult(flatRecordToResult(record));
      setOpenModule("ai_detection");
    } catch (err) {
      setReplayError(friendlyError(err, "Could not open this analysis. Re-upload the paper for a fresh verification."));
    } finally {
      setReplayLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-white/90 backdrop-blur border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-gradient-to-br from-blue-600 to-indigo-700 text-white font-bold flex items-center justify-center">V</div>
            <div>
              <p className="font-bold text-slate-900 leading-tight">VeriPaper</p>
              <p className="text-[11px] text-slate-500 leading-tight">Research Verification Suite</p>
            </div>
          </div>
          <nav className="hidden sm:flex items-center gap-1 text-sm">
            <a href="#analyze" className="px-3 py-2 rounded-lg text-slate-600 hover:bg-slate-100">Analyze</a>
            <a href="#history" className="px-3 py-2 rounded-lg text-slate-600 hover:bg-slate-100">History</a>
            <a href="#method" className="px-3 py-2 rounded-lg text-slate-600 hover:bg-slate-100">How it works</a>
          </nav>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 py-8 space-y-8">
        {/* Hero */}
        <section className="text-center max-w-2xl mx-auto">
          <span className="inline-block text-xs font-semibold px-3 py-1 rounded-full bg-blue-100 text-blue-700 mb-4">
            ✦ VeriPaper — the 6-in-1 integrity check
          </span>
          <h1 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
            Is your research paper really <span className="text-blue-600">credible?</span>
          </h1>
          <p className="text-slate-600 mt-3">
            One upload. Six checks: plagiarism, AI authorship, citation authenticity, statistical integrity, academic writing standards, and provenance-chain verification — every result explained in plain language.
          </p>
        </section>

        {/* Upload */}
        <section id="analyze" className="card bg-white border border-slate-200 shadow-sm">
          <form onSubmit={runAnalysis} className="space-y-4">
            <label className="flex flex-col items-center justify-center border-2 border-dashed border-slate-300 rounded-xl p-8 text-center cursor-pointer hover:border-blue-500 hover:bg-blue-50/40 transition-colors">
              <input type="file" accept=".pdf,.docx,.txt" className="hidden" onChange={(e) => setFile(e.target.files?.[0] || null)} />
              <span className="text-3xl">📄</span>
              <p className="font-semibold text-slate-900 mt-2 text-sm break-all">{file ? file.name : "Drop your paper here, or click to browse"}</p>
              <p className="text-xs text-slate-500 mt-1">PDF, DOCX, or TXT · max 15 MB · processed privately, never shared</p>
            </label>
            {error && <p className="text-xs font-medium text-red-700 bg-red-50 border border-red-200 rounded-lg p-3">⚠ {error}</p>}
            {loading && (
              <div className="space-y-2">
                <div className="flex justify-between text-xs text-slate-600">
                  <span>Analyzing… (parsing · AI model · similarity corpus · CrossRef)</span>
                  <span>{Math.round(progress)}%</span>
                </div>
                <ProgressBar value={progress} color="bg-blue-500" />
              </div>
            )}
            <button type="submit" disabled={loading || !file} className="w-full btn-primary disabled:opacity-50 disabled:cursor-not-allowed">
              {loading ? "Analyzing…" : "Run Full Verification"}
            </button>
          </form>
        </section>

        {/* Results */}
        {result && (
          <section className="space-y-6">
            {/* Verdict banner */}
            <div className="card bg-white border border-slate-200 shadow-sm">
              <div className="flex flex-col sm:flex-row items-center gap-6">
                <GradeGauge score={result.overall_research_credibility} size={110} />
                <div className="flex-1 text-center sm:text-left">
                  <p className="text-xs uppercase tracking-wider text-slate-500 font-semibold mb-1">Overall credibility</p>
                  <h2 className="text-2xl font-bold text-slate-900">{vMeta.title}</h2>
                  <p className="text-sm text-slate-600 mt-2 max-w-xl">{vMeta.desc}</p>
                  <div className="mt-3 flex flex-wrap gap-2 justify-center sm:justify-start">
                    <span className={`text-xs px-2.5 py-1 rounded-full border font-medium ${vMeta.badge}`}>{result.verdict}</span>
                    <span className="text-xs px-2.5 py-1 rounded-full bg-slate-100 text-slate-600">{result.word_count} words · {result.section_count} sections · {result.filename}</span>
                  </div>
                </div>
              </div>
              {(result.action_items?.length > 0 || result.risk_triggers?.length > 0) && (
                <div className="mt-5 border-t border-slate-100 pt-4">
                  <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Recommended next steps</p>
                  <ol className="space-y-1.5">
                    {result.action_items.map((item, i) => (
                      <li key={i} className="flex gap-2 text-sm text-slate-700">
                        <span className="font-semibold text-blue-600">{i + 1}.</span> {item}
                      </li>
                    ))}
                  </ol>
                </div>
              )}
            </div>

            {/* Module score tabs */}
            <div className="grid grid-cols-5 gap-2">
              {modules.map((m) => {
                const r = riskLabel(m.score);
                const active = openModule === m.key;
                return (
                  <button
                    key={m.key}
                    onClick={() => setOpenModule(m.key)}
                    className={`card text-center py-3 px-1 border transition-colors ${active ? "border-blue-500 ring-1 ring-blue-500 bg-blue-50/40" : "bg-white border-slate-200 hover:border-slate-300"}`}
                  >
                    <p className="text-[11px] font-semibold text-slate-500 leading-tight">{MODULE_TITLES[m.key]}</p>
                    <p className={`text-lg font-bold leading-tight mt-1 ${r.cls}`}>{Math.round(m.score)}</p>
                    <p className={`text-[10px] leading-tight mt-0.5 ${r.cls}`}>{r.text}</p>
                  </button>
                );
              })}
            </div>

            {/* Module detail */}
            <ErrorBoundary fallback={modulePanelFallback}>
            <div className="card bg-white border border-slate-200 shadow-sm">
              <div className="flex items-start justify-between flex-wrap gap-3 border-b border-slate-100 pb-4 mb-4">
                <div>
                  <h3 className="font-bold text-slate-900">{MODULE_TITLES[openModule]}</h3>
                  <p className="text-xs text-slate-500 mt-1 max-w-xl">{MODULE_EXPLAIN[openModule]}</p>
                </div>
                <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
                  {openModule === "statistics" ? "Integrity: " : openModule === "citation" || openModule === "writing" || openModule === "provenance" ? "Score: " : "Risk: "}
                  {Math.round(modules.find((m) => m.key === openModule).score)} / 100
                </span>
              </div>
              {openModule === "plagiarism" && <PlagiarismPanel data={result.plagiarism} />}
              {openModule === "ai_detection" && <AIPanel data={result.ai_detection} />}
              {openModule === "citation" && <CitationPanel data={result.citation} />}
              {openModule === "statistics" && <StatisticsPanel data={result.statistics} />}
              {openModule === "writing" && <WritingPanel data={result.writing} />}
              {openModule === "provenance" && <ProvenancePanel data={result.provenance} />}
            </div>
            </ErrorBoundary>

            {/* Sections & exports */}
            <div className="grid lg:grid-cols-[1fr_320px] gap-6">
              <div className="card bg-white border border-slate-200 shadow-sm">
                <h3 className="font-bold text-slate-900 mb-3 text-sm">Detected structure</h3>
                <div className="flex flex-wrap gap-2">
                  {result.sections.map((s, i) => (
                    <div key={i} className="text-xs px-2.5 py-1.5 bg-slate-50 border border-slate-200 rounded-lg">
                      <span className="font-medium text-slate-800">{s.heading}</span>
                      <span className="text-slate-500"> · {s.word_count}w</span>
                    </div>
                  ))}
                </div>
              </div>
              <div className="card bg-white border border-slate-200 shadow-sm space-y-3">
                <h3 className="font-bold text-slate-900 text-sm">Export evidence</h3>
                <button onClick={() => downloadPDF(result.report_path)} className="btn-primary w-full text-sm">📥 PDF Report</button>
                <button onClick={() => downloadCSV(result)} className="btn-secondary w-full text-sm">CSV Export</button>
                <button onClick={() => downloadJSON(result)} className="btn-secondary w-full text-sm">JSON Export</button>
              </div>
            </div>
          </section>
        )}

        {/* History */}
        <section id="history" className="card bg-white border border-slate-200 shadow-sm">
          <h3 className="font-bold text-slate-900 mb-4">Analysis history</h3>
          {serverHistory.length === 0 ? (
            <p className="text-sm text-slate-500 py-8 text-center">No analyses yet — your first verification will appear here.</p>
          ) : (
            <div className="space-y-2">
              {serverHistory.map((h, i) => (
                <button
                  key={h.id || i}
                  onClick={() => openOld(h)}
                  className="w-full text-left flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-200 hover:border-blue-300 hover:bg-blue-50 transition-colors disabled:opacity-60"
                  disabled={replayLoading}
                >
                  <div>
                    <p className="text-sm font-medium text-slate-900">{h.filename}</p>
                    <p className="text-[11px] text-slate-500 mt-0.5">{new Date(h.analyzed_at).toLocaleString()}</p>
                  </div>
                  <span className="text-xs font-semibold text-slate-600">{Math.round(h.overall_research_credibility)}% · {h.verdict}</span>
                </button>
              ))}
            </div>
          )}
          {replayError && (
            <p className="text-xs text-red-600 bg-red-50 border border-red-200 rounded-lg p-3 mt-3">{replayError}</p>
          )}
          {replayLoading && (
            <p className="text-xs text-slate-500 mt-3">Opening previous analysis…</p>
          )}
          {localHistory.length > 0 && (
            <p className="text-[11px] text-slate-400 mt-3">Also saved locally in this browser ({localHistory.length} entries).</p>
          )}
        </section>

        {/* How it works */}
        <section id="method" className="space-y-4">
          <h3 className="font-bold text-slate-900 text-lg">How VeriPaper verifies a paper</h3>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            {Object.entries(MODULE_EXPLAIN).map(([key, text]) => (
              <div key={key} className="card bg-white border border-slate-200">
                <p className="text-sm font-bold text-slate-900">{MODULE_TITLES[key]}</p>
                <p className="text-xs text-slate-600 mt-2 leading-relaxed">{text}</p>
              </div>
            ))}
          </div>
          <div className="card bg-amber-50 border border-amber-200 text-xs text-amber-800 p-4">
            <span className="font-semibold">Important:</span> every score is a likelihood signal generated by statistical models — not legal proof of misconduct. Use VeriPaper to triage and prioritize manual review, never as the sole basis for an accusation.
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white py-8 mt-8">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-slate-500">
          <p>© 2026 VeriPaper — Research Verification Suite</p>
          {config?.ai_detection && (
            <p>AI model: {config.ai_detection.model_version?.split("/").pop() || config.ai_detection.model_version} (validation F1 {config.ai_detection.metrics?.f1})</p>
          )}
        </div>
      </footer>

      {/* Onboarding */}
      {showOnboard && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => { setShowOnboard(false); localStorage.setItem("veripaper_onboarded", "1"); }}>
          <div className="bg-white rounded-2xl shadow-xl max-w-md w-full p-6" onClick={(e) => e.stopPropagation()}>
            <h3 className="text-lg font-bold text-slate-900">Welcome to VeriPaper 👋</h3>
            <p className="text-sm text-slate-600 mt-2">Upload any research paper (PDF/DOCX/TXT) and we'll check five things at once:</p>
            <ul className="mt-3 space-y-1.5 text-sm text-slate-700">
              {Object.values(MODULE_TITLES).map((t, i) => (
                <li key={i} className="flex gap-2"><span className="text-blue-600 font-bold">{i + 1}.</span> {t}</li>
              ))}
            </ul>
            <p className="text-xs text-slate-500 mt-4">Scores are signals to guide review — not proof.</p>
            <button
              onClick={() => { setShowOnboard(false); localStorage.setItem("veripaper_onboarded", "1"); }}
              className="btn-primary w-full mt-4"
            >
              Got it — start analyzing
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
